name: Daily Commit

on:
  schedule:
    # Runs at 12:00 UTC (adjust as needed)
    - cron: '0 12 * * *'
  
  # Allow manual triggers from the Actions tab
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Fetch all history for all tags and branches
          fetch-depth: 0
      
      - name: Setup Git identity
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
      
      - name: Create daily update
        run: |
          # Get date information
          DATE=$(date +"%Y-%m-%d")
          TIME=$(date +"%H:%M:%S")
          RANDOM_ID=$((1000 + $RANDOM % 9000))
          
          # Update file with daily content
          echo "Daily update: $DATE $TIME #$RANDOM_ID" >> daily-update.txt
      
      - name: Commit and push changes
        run: |
          # Add modified files
          git add daily-update.txt
          
          # Create commit with today's date
          git commit -m "Daily update: $(date +"%Y-%m-%d")"
          
          # Push to the repository using token for authentication
          git push origin ${{ github.ref_name }}
        env:
          # Uses GitHub's automatically provided GITHUB_TOKEN
          # No need to create a personal access token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
